# Generated by Django 5.1.6 on 2025-03-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_meme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
