# Generated by Django 5.1.6 on 2025-03-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_meme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='image_height',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='meme',
            name='image_width',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='uploads', width_field='image_width'),
        ),
    ]
